### ISSUE TITLE
New Update BREAKS ELEMENTOR

### ISSUE THREAD

**Issue by poompah** [ahmedkaludi/Easy-Table-of-Contents#519]
Noticed issues with an Elemenotr built website this AM. Deactivating your plugin removed the issues. 

Your new update has resulted in the following: 
1) All lists (including such as icon lists etc.) displaying as list-style-type: disc
2) Any formatting regarding spacing of lists is lost
3) Forminator forms failing to load
4) All separators displaying lines retain their height but width is 0 -- css alert "use a different display type" suggesting that display: inline is causing a problem with the width display. Changing this to display:block makes NO difference.

Surely you guys test this stuff before you release it? I guess there are a lot of possible scenarios to cover. 
This is exactly why I don't like to use plugins built by small independents.

**Comment by poompah** [comment]
Shane because this was a useful plugin.

**Comment by Sanjeevsetu** [comment]
Hi @poompah 

Extremely sorry for it. Could you please help us to find the cause. Please provide us the post urls with issues on it or contact our support for better debug.

**Comment by poompah** [comment]
I have deactivated the plugin as I cannot have this site borken in the way it was – so no Point in sending you to the pages to see.ALL pages were affected that has lists, underlines or forms which was pretty much every page. The issue was identical in both Chrome and Microsoft Edge browsers. Here are some screenshots: This first is the website display vs Elementor display   And for a form (Home page on https://thainee.spa) not loading. Sent from Mail for Windows From: Sanjeev KumarSent: Wednesday, 5 July 2023 08:42To: ahmedkaludi/Easy-Table-of-ContentsCc: poompah; MentionSubject: Re: [ahmedkaludi/Easy-Table-of-Contents] New Update BREAKS ELEMENTOR (Issue #519) Hi @poompahExtremely sorry for it. Could you please help us to find the cause. Please provide us the post urls with issues on it or contact our support for better debug.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by Sanjeevsetu** [comment]
Hi @poompah 

We understand your concern. There are few users like you have faced the issue and we really want to solve them. I can not see any screenshots here. Can you resend them??

**Comment by poompah** [comment]
Attached Sent from Mail for Windows From: Sanjeev KumarSent: Wednesday, 5 July 2023 09:27To: ahmedkaludi/Easy-Table-of-ContentsCc: poompah; MentionSubject: Re: [ahmedkaludi/Easy-Table-of-Contents] New Update BREAKS ELEMENTOR (Issue #519) Hi @poompahWe understand your concern. There are few users like you have faced the issue and we really want to solve them. I can not see any screenshots here. Can you resend them??—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by Sanjeevsetu** [comment]
Hi @poompah 

We have just released a patch. Kindly update to our latest v 2.0.51.1 and let us know..

Thank you so much.

**Comment by nickdelicto** [comment]
I have the latest v 2.0.51.1 but still facing a similar problem. check here- https://thecollegeapplication.com/accelerated-nursing-programs-in-pennsylvania/

**Comment by Sanjeevsetu** [comment]
Hi @nickdelicto 

I can see on given link that toc is working fine and it does not seem to issue like @poompah . Can you re check it and know the exact issue?

**Comment by Sanjeevsetu** [comment]
Hi @poompah & @nickdelicto 

Could you please confirm on it??

**Comment by nickdelicto** [comment]
Hey @Sanjeevsetu, to solve the problem I stopped using the plugin as a reusable block. I use generatepress theme.

**Comment by poompah** [comment]
I switched to another plugin, which meets my needs thanks. I may may check your plugin in future, but for now please do not ask me to run checks. Thanks. Sent from Mail for Windows From: Sanjeev KumarSent: Friday, 7 July 2023 10:21To: ahmedkaludi/Easy-Table-of-ContentsCc: poompah; MentionSubject: Re: [ahmedkaludi/Easy-Table-of-Contents] New Update BREAKS ELEMENTOR (Issue #519) Hi @poompah & @nickdelictoCould you please confirm on it??—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by Sanjeevsetu** [comment]
Hi @nickdelicto 

Thanks for the confirmation.
